name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Prepare Lambda artifacts
        run: |
          mkdir -p lambda-artifacts
          cp target/commerce-maven-0.0.1-SNAPSHOT-lambda.jar lambda-artifacts/

      - name: Upload JAR to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          aws-region: eu-west-1
          function-name: walkre-ecommerce-backend
          code-artifacts-dir: lambda-artifacts
          role: arn:aws:iam::291628183865:role/walkre-lambda-execution-role
          handler: com.elwalkre.commerce_maven.StreamLambdaHandler::handleRequest
          runtime: java21
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1

